### PR TITLE
first review stage-2

### PR DESCRIPTION
**Pull request by Yaronamir86**
hey, all criteria set and done, waiting for comment, thanks in advance

### CODE REVIEW

**Comment by Yaronamir86** [comment]
hi, in my project i dont have this error,  so i cleared cached on git and i hope now it will be fine

**Comment by ImaliaNsk** [comment]
Great job with your diploma project! Some issues will be necessary to correct, but on the whole it looks pretty good! I'm sure the issues below will be easy to fix, they are mostly minor flaws!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://skr.sh/sH0aDwEyz3s Should be uppercase
* `main__title` incorrect font-size and alignment

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* https://skr.sh/sH0WzelenHn Text is cropped
* https://skr.sh/sH0ArUOhAzy

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* footer should contain working links opening in new tabs

- [x]  Classes are named according to BEM specifications.

* Elements used outside of the block https://skr.sh/sH0umIFAMjm https://skr.sh/sH09N05CVOm https://skr.sh/sH0hm0FpF9l

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* There should be one h1 per page

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.

* "Registration successful"

- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover effect on a card bookmark from the mockup: https://skr.sh/sH0y9Tkgpph
* Hover effect on trash can icon from the mockup: https://skr.sh/sH0VdF6xUdE
* "Search" button needs hover effect and "active" state
* "Show more" button needs a hover effect

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* Please correct all similar cases https://skr.sh/sH0MN8xeQGK

- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 44

**Comment by Yaronamir86** [comment]
hi, thank you for your comments, i fixed all the issues.
 regarding the  comment "Elements used outside of the block" in my project i used components inside components and not as you saw and sent in the picture, so i dont know what cause this issue.
and regarding the comment "The popup windows have opening and closing functionality implemented.
("Registration successful")" the functionality is inside "context" folder at "modalContext" file. waiting for your next commens and thanks in advance!

**Comment by ImaliaNsk** [comment]
Hi! Thanks for the corrections, good job! Some issues still require your attention, though. I've left a more detailed comment about BEM below. Please, also fix the issues with text cropping and overlapping on intermediate screens and desktop.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://skr.sh/sH0aDwEyz3s Should be uppercase
* Text overlaps https://skr.sh/sH1Ja3ydDwB

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* https://skr.sh/sH0WzelenHn Text is cropped
* https://skr.sh/sH0ArUOhAzy

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* Elements used outside of the block https://skr.sh/sH0umIFAMjm https://skr.sh/sH09N05CVOm https://skr.sh/sH0hm0FpF9l and a lot of other cases like this on saved-news page. Components form a DOM tree, and all elements that have class names are parts of BEM class hierarchy. Currently, many elements have classes represented by BEM elements, but they are not nested inside their block. This is a BEM violation, element can be used only inside its block. In this sense, a component should normally correspond to a BEM block. For example, you render `about` section with a div container with class name `about__wrapper`, which is an element, and it's not inside a block `about`. Would be better to use a class name `about` for the wrapper, this will fix the BEM hierarchy error.

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.

* Please correct all similar cases https://skr.sh/sH0MN8xeQGK

- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 67

**Comment by Yaronamir86** [comment]
hey again and thank you so much for the great comments, i fixed all the issues and i attached screen shot from my project regarding the BEM issue to show you that in my work i'm importing components and not using elements, which is not a vaiolation of the BEM structure, i already cleaned cached so i dont know what can cause this differences betweem what i see and what you see.. thank you again, waiting for your comments!

**Comment by ImaliaNsk** [comment]
The project is accepted, thanks for the corrections! Good luck on the next stage!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.

* Elements used outside of the block https://skr.sh/sH0umIFAMjm https://skr.sh/sH09N05CVOm https://skr.sh/sH0hm0FpF9l and a lot of other cases like this on saved-news page. The issue is not related to the names of components you use, only to the names of your classes. I see the screenshot, and yes, this is exactly what I see when I open your project in IDE. However, the DOM tree built in the browser shows that many block names are actually missing (this means that there's no parent element with class `block` to contain elements with `block__element` names). I'll give an example: https://skr.sh/sH1HNQvJffB This is the jsx code for `about` component, this is how it looks in the DOM tree: https://skr.sh/sH1f67ULbpQ. All elements are used without BEM block `about`. This could be fixed with changing name `about__wrapper` to `about` https://skr.sh/sH1Mmq3VOoi. This is a correct BEM structure: all elements are inside a corresponding block.

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* Please correct all similar cases https://skr.sh/sH1eCClBdEo

- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 92

**Comment by Yaronamir86** [comment]
hey thank you for your patience and for the comments, i finally got my mistakes and fix that BEM vaiolation and the fonts issues, hope to get 100 this time, thanks in advance!

**Pull request merged**
